name: OnlineGroceryStore
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  shared_preferences: ^0.5.12+4
  vibration: ^1.7.3
  page_transition: ^1.1.7+6
  flushbar: ^1.10.4
  fluttertoast: ^7.1.6
  progress_dialog: ^1.2.4
  animate_do: ^1.7.5
  eva_icons_flutter: ^2.0.1
  cached_network_image: ^2.3.3
  blur: ^1.0.1
  provider: ^4.3.2+2
  intl_phone_field: ^1.4.2
  international_phone_input: ^1.0.4
  rules: ^1.2.0+1
  pinput: ^0.2.0
  geolocator: ^6.1.13
  geocoding: ^1.0.5
  custom_navigation_bar: ^0.7.0
  flutter_icons:
  ant_icons: ^1.0.0
  fluentui_system_icons: ^1.1.91
  carousel_pro: ^1.0.0
  dots_indicator: ^1.2.0
  floating_action_row: ^0.1.0
  backdrop: ^0.4.7
  backdrop_modal_route: ^1.1.0
  carousel_slider: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.8.1
  flutter_native_splash: ^0.1.9

flutter_native_splash:
  image: assets/image/splash_logo.png
  color: "53b175"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image/header_image.png
    - assets/image/icon_color.png
    - assets/image/icon.png
    - assets/image/map_pin.png
    - assets/image/splash_logo.png
    - assets/image/welcome.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Bold.ttf
        - asset: assets/fonts/Gilroy-Heavy.ttf
        - asset: assets/fonts/Gilroy-Light.ttf
        - asset: assets/fonts/Gilroy-Medium.ttf
        - asset: assets/fonts/Gilroy-Regular.ttf

  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
